language: scala
sudo: false
scala:
  - 2.12.5
jdk:
  - oraclejdk8
env:
  global:
    - MAIN_SCALA_VERSION=2.12.5
cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt
script:
  - sbt clean coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)